[package]
name = "nitro_legacy_inventory"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "nitro_legacy_inventory"

[dependencies]
anchor-lang = { workspace = true }
anchor-spl = { version = "0.29.0", optional = true }